version: '3.8'

services:
  model:
    build: 
      context: ./predict
      dockerfile: Dockerfile
    container_name: model_service
    expose:
      - "5001"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    depends_on:
      - model
      - db
    ports:
      - "8000:8000"
    environment:
      - MODEL_URL=http://model:5001/predict
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=predictions

  db:
    image: mysql:8.0
    container_name: db_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: predictions
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
